# -*- coding: utf-8 -*-
"""Classification Project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IHEaxRbYxq18qkmgIeBd3UygG6KwCku6
"""

# ==============================================================================
# Python Script converted from Jupyter Notebook: Classification Project.ipynb
# ==============================================================================

# ==============================================================================
# Cell 1:
# ==============================================================================
#import the libraries
from matplotlib import pyplot
from pandas import read_csv
from pandas import set_option
from pandas import DataFrame
from pandas.plotting import scatter_matrix
from numpy import array
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from pickle import dump
from pickle import load
import matplotlib.pyplot as plt
import numpy


# ==============================================================================
# Cell 2:
# ==============================================================================
# #### Load the data


# ==============================================================================
# Cell 3:
# ==============================================================================
# Load CSV using Pandas
filename = 'pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=names)
print(data.shape)


# ==============================================================================
# Cell 4:
# ==============================================================================
# #### Desrciptive Stats


# ==============================================================================
# Cell 5:
# ==============================================================================

filename = "pima-indians-diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=names)


# ==============================================================================
# Cell 6:
# ==============================================================================
# Data Types for Each Attribute
types = data.dtypes
print(types)


# ==============================================================================
# Cell 7:
# ==============================================================================
# Statistical Summary
set_option('display.width', 100)
set_option('precision', 3)
description = data.describe()
print(description)


# ==============================================================================
# Cell 8:
# ==============================================================================
# Pairwise Pearson correlations
correlations = data.corr(method='pearson')
print(correlations)


# ==============================================================================
# Cell 9:
# ==============================================================================
# Class proportion
class_counts = data.groupby('class').size()
print(class_counts)


# ==============================================================================
# Cell 10:
# ==============================================================================
# #### Data Visualization


# ==============================================================================
# Cell 11:
# ==============================================================================
# Histograms
data.hist(figsize=(12, 8))
plt.show()


# ==============================================================================
# Cell 12:
# ==============================================================================
# Density plots
data.plot(kind='density', subplots=True, layout=(3,3), sharex=False, figsize=(12, 8))
pyplot.show()


# ==============================================================================
# Cell 13:
# ==============================================================================
# Box and Whisker Plots
data.plot(kind='box', subplots=True, layout=(3,3), sharex=False, sharey=False, figsize=(12, 8))
pyplot.show()


# ==============================================================================
# Cell 14:
# ==============================================================================
# Correlation matrix plot
fig = pyplot.figure(figsize=(8, 8))
ax = fig.add_subplot(111)
cax = ax.matshow(data.corr(), vmin=-1, vmax=1, interpolation='none')
fig.colorbar(cax)
ticks = numpy.arange(0,9,1)
ax.set_xticks(ticks)
ax.set_yticks(ticks)
ax.set_xticklabels(names)
ax.set_yticklabels(names)
pyplot.show()


# ==============================================================================
# Cell 15:
# ==============================================================================
# Scatter Plot Matrix
scatter_matrix(data, figsize=(12, 12))
pyplot.show()


# ==============================================================================
# Cell 16:
# ==============================================================================
# #### Prepare Data For Algorithms


# ==============================================================================
# Cell 17:
# ==============================================================================
# Separate data into X and y
array = data.values
X = array[:,0:8]
Y = array[:,8]

# Rescale data (Standardization)
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

# summarize transformed data
# set_option('precision', 3)
# rescaled_data = DataFrame(rescaledX)
# print(rescaled_data.head(5))


# ==============================================================================
# Cell 18:
# ==============================================================================
# #### Evaluate Algorithms


# ==============================================================================
# Cell 19:
# ==============================================================================
# Prepare models
models = []
models.append(('LR', LogisticRegression(max_iter=200)))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))

# Evaluate each model in turn
results = []
names = []
scoring = 'accuracy'
for name, model in models:
    kfold = KFold(n_splits=10, random_state=7, shuffle=True)
    cv_results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)


# ==============================================================================
# Cell 20:
# ==============================================================================
# Compare Algorithms
fig = pyplot.figure()
fig.suptitle('Algorithm Comparison')
ax = fig.add_subplot(111)
pyplot.boxplot(results)
ax.set_xticklabels(names)
pyplot.show()


# ==============================================================================
# Cell 21:
# ==============================================================================
# Evaluate Algorithms with Rescaled Data


# ==============================================================================
# Cell 22:
# ==============================================================================
# Prepare models with rescaled data
models = []
models.append(('LR', LogisticRegression(max_iter=200)))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))

# Evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = KFold(n_splits=10, random_state=7, shuffle=True)
    cv_results = cross_val_score(model, rescaledX, Y, cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)


# ==============================================================================
# Cell 23:
# ==============================================================================
# Compare Algorithms with Rescaled Data
fig = pyplot.figure()
fig.suptitle('Scaled Algorithm Comparison')
ax = fig.add_subplot(111)
pyplot.boxplot(results)
ax.set_xticklabels(names)
pyplot.show()


# ==============================================================================
# Cell 24:
# ==============================================================================
# #### Improve Accuracy with Tuning


# ==============================================================================
# Cell 25:
# ==============================================================================
# Tune KNN
# The following lines are redundant but kept to mirror the notebook's cell structure:
array = data.values
X = array[:,0:8]
Y = array[:,8]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
# End of redundant lines

# Tune KNN
n_neighbors = [1,3,5,7,9,11,13,15,17,19,21]
param_grid = dict(n_neighbors=n_neighbors)
model = KNeighborsClassifier()
kfold = KFold(n_splits=10, random_state=7, shuffle=True)
grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=kfold)
grid_result = grid.fit(rescaledX, Y)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))


# ==============================================================================
# Cell 26:
# ==============================================================================
# Tune SVM
# The following lines are redundant but kept to mirror the notebook's cell structure:
array = data.values
X = array[:,0:8]
Y = array[:,8]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
# End of redundant lines

# Tune SVM
c_values = [0.1, 0.3, 0.5, 0.7, 0.9, 1.0, 1.3, 1.5, 1.7, 2.0]
kernel_values = ['linear', 'poly', 'rbf', 'sigmoid']
param_grid = dict(C=c_values, kernel=kernel_values)
model = SVC(gamma='auto')
kfold = KFold(n_splits=10, random_state=7, shuffle=True)
grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=kfold)
grid_result = grid.fit(rescaledX, Y)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))


# ==============================================================================
# Cell 27:
# ==============================================================================
# #### Finalize Model


# ==============================================================================
# Cell 28:
# ==============================================================================
# Finalize Model with SVM
# The following lines are redundant but kept to mirror the notebook's cell structure:
array = data.values
X = array[:,0:8]
Y = array[:,8]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
# End of redundant lines

# split data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(rescaledX, Y, test_size=0.33, random_state=7)
# Fit the model on 67%
model = SVC(C=1.5, kernel='rbf', gamma='auto')
model.fit(X_train, Y_train)
result = model.score(X_test, Y_test)
print("Accuracy (SVM-RBF): %.3f" % result)


# ==============================================================================
# Cell 29:
# ==============================================================================
# Finalize Model with LR
# The following lines are redundant but kept to mirror the notebook's cell structure:
array = data.values
X = array[:,0:8]
Y = array[:,8]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=7)
# End of redundant lines

# Fit the model on 33%
model = LogisticRegression(max_iter=200)
model.fit(X_train, Y_train)

# save the model to disk
filename = 'finalized_model.sav'
dump(model, open('filename', 'wb'))

# some time later...

# load the model from disk
loaded_model = load(open('filename', 'rb'))
result = loaded_model.score(X_test, Y_test)
print(result)


# ==============================================================================
# Cell 30:
# ==============================================================================
# #### Prediction


# ==============================================================================
# Cell 31:
# ==============================================================================
# Make predictions using the finalized model
# load the model from disk
loaded_model = load(open('filename', 'rb'))
# make a single prediction
Xnew = [[1, 120, 70, 30, 0, 32.5, 0.5, 30]] # Example data
ynew = loaded_model.predict(Xnew)
print("Predicted Class (Logistic Regression): %s" % ynew[0])